-- Role: postgres
-- DROP ROLE IF EXISTS postgres;

CREATE ROLE postgres WITH
    LOGIN
    SUPERUSER
    INHERIT
    CREATEDB
    CREATEROLE
    REPLICATION
    ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:thTahL35LdIQD+VJOnnvIQ==$dQOkWqu1M2zSUS4oIJr05XNBfjPyeBY99tCQtaupuXY=:pD7tJAYzp8zh5BULkg+VICz4+A8v9AaePdGx3ZvRmgE=';
