-- Table: public.MOVIES_LIST

-- DROP TABLE IF EXISTS public."MOVIES_LIST";

CREATE TABLE IF NOT EXISTS public."MOVIES_LIST"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    original_title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    russian_title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    genre genre[],
    imdb_id character varying(255) COLLATE pg_catalog."default",
    year integer,
    quality quality,
    file_path character varying(512) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT id PRIMARY KEY (id)
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."MOVIES_LIST"
    OWNER to postgres;
